using System.Globalization;
using System.Windows;

namespace StarRupturePlanner.Services;

public static class UiText
{
    private static readonly Dictionary<string, string> Fallback = new()
    {
        ["Text.InvalidConnection"] = "Invalid connection",
        ["Text.InvalidInput"] = "Invalid input",
        ["Text.TransportTierMissing"] = "transport tier missing",
        ["Text.MeetsDemand"] = "meets demand",
        ["Text.RailOverCapacity"] = "rail over capacity",
        ["Text.Short"] = "short",
        ["Text.Item"] = "Item",
        ["Text.From"] = "From",
        ["Text.Throughput"] = "Throughput",
        ["Text.Transport"] = "Transport",
        ["Text.Ok"] = "OK",
        ["Text.OverCapacity"] = "over capacity",
        ["Text.NoRailTierAvailable"] = "no rail tier available",
        ["Text.ExceedsAvailableRails"] = "exceeds available rails",
        ["Text.Max"] = "max",
        ["Text.NoRecipeSelected"] = "No recipe selected. Ports are disabled.",
        ["Text.Building"] = "Building",
        ["Text.Machines"] = "Machines",
        ["Text.Output"] = "Output",
        ["Text.RecipeBase"] = "Recipe base",
        ["Text.Priority"] = "Priority",
        ["Text.None"] = "None",
        ["Text.Available"] = "Available",
        ["Text.Level"] = "level",
        ["Text.LockedByCorporationLevels"] = "is locked by corporation levels",
        ["Text.LockedRequires"] = "locked: requires",
        ["Text.NoProductionShortages"] = "No production shortages",
        ["Text.Issues"] = "ISSUES",
        ["Text.NotAvailableForConnection"] = "is not available for connection with current corporation levels.",
        ["Text.Temp"] = "temp",
        ["Text.UnselectedMachine"] = "Unselected machine",
        ["Text.RecipeNotSelected"] = "Recipe not selected",
        ["Text.LockedByCorporations"] = "Locked by corporations",
        ["Text.CountSource"] = "Count {0} source",
        ["Text.CountPriority"] = "Count {0} {1}",
        ["Text.SelectRecipeToActivatePorts"] = "Select a recipe in the inspector to activate ports.",
        ["Text.InputsUpper"] = "INPUTS",
        ["Text.OutputsUpper"] = "OUTPUTS",
        ["Text.BlueprintSource"] = "Blueprint source",
        ["Text.ExternalOutputsCount"] = "External outputs: {0}",
        ["Text.BlueprintSourceDescription"] = "Outputs from an existing saved scheme.",
        ["Text.BlueprintInspectorDescription"] = "Blueprint source from a saved scheme. It has outputs only and does not consume inputs.",
        ["Text.OutputAvailableRate"] = "{0}: {1:g}/min available",
        ["Text.RecipeBaseInputsBypassed"] = "Recipe base: {0:g}/min ({1}). Inputs are bypassed; output still scales with machine count.",
        ["Text.RecipeBaseInputsScale"] = "Recipe base: {0:g}/min ({1}). Inputs scale with machine count.",
        ["Text.InputsBypassedOnlyOutput"] = "Inputs bypassed by Only output.",
        ["Text.InputRequirement"] = "{0}: {1:g}/min required, {2:g}/min delivered",
        ["Text.InputRequirementShort"] = "SHORT {0}: {1:g}/min required, {2:g}/min delivered",
        ["Text.Connection"] = "Connection",
        ["Text.Scheme"] = "Scheme",
        ["Text.CorporationDataUnavailable"] = "Corporation data is not available yet.",
        ["Text.MaxLevel"] = "Max level {0}",
        ["Text.NoRailTiersConfigured"] = "No rail tiers are configured.",
        ["Text.NoRailTiersUnlocked"] = "No rail tiers are currently unlocked.",
        ["Text.MaxAvailableRail"] = "Max available: {0} ({1:g}/min)",
        ["Text.RailAvailableTooltip"] = "Available for any connection that needs this capacity.",
        ["Text.RailTierAvailable"] = "{0} {1:g}/min available",
        ["Text.RailTierLocked"] = "{0} {1:g}/min locked",
        ["Text.Requires"] = "Requires: {0}",
        ["Text.OnlyOutput"] = "Only output",
        ["Text.SchemeOutput"] = "Scheme output",
        ["Text.Surplus"] = "Surplus +{0:g}/min",
        ["Text.NoSchemeOutputsMarked"] = "No scheme outputs marked",
        ["Text.Comment"] = "Comment",
        ["Text.DeleteScheme"] = "Delete scheme",
        ["Text.DeleteSchemeConfirm"] = "Delete saved scheme \"{0}\"? This cannot be undone.",
        ["Text.SchemeName"] = "Scheme name",
        ["Text.Name"] = "Name",
        ["Text.ThemeSystem"] = "System",
        ["Text.ThemeDark"] = "Dark",
        ["Text.ThemeLight"] = "Light",
        ["Text.LanguageEnglish"] = "English",
        ["Text.LanguageRussian"] = "Russian",
        ["Text.LanguageGerman"] = "German",
        ["Text.LanguageUkrainian"] = "Ukrainian",
        ["Text.SelectFontFamily"] = "Select a font family.",
        ["Text.InvalidSettings"] = "Invalid settings",
        ["Text.ApiStartup"] = "API startup",
        ["Text.FontSizeRange"] = "Font size must be between 8 and 32.",
        ["Text.ApiPortRange"] = "API port must be a number from 1 to 65535.",
        ["Text.InvalidWpfColor"] = "Color must be a valid WPF color, for example #F4F0E8.",
        ["Text.ChooseSchemeFolder"] = "Choose StarRupture scheme folder",
        ["Text.AddSchemeJson"] = "Add scheme JSON",
        ["Text.SchemeJsonFilter"] = "Scheme JSON (*.json)|*.json",
        ["Text.SchemeAlreadyExists"] = "A scheme named \"{0}\" already exists. Choose Yes to replace it, No to keep both, or Cancel to stop.",
        ["Metric.TotalPower"] = "Total Power",
        ["Metric.Temperature"] = "Temperature",
        ["Status.StartingApi"] = "Starting local API...",
        ["Status.LoadedRecipes"] = "Loaded {0} recipes.",
        ["Status.ApiStartupFailed"] = "API startup failed: {0}",
        ["Status.NewEmptyScheme"] = "New empty scheme.",
        ["Status.Opened"] = "Opened {0}.",
        ["Status.CouldNotOpenScheme"] = "Could not open scheme: {0}",
        ["Status.Saved"] = "Saved {0}.",
        ["Status.SettingsSaved"] = "Settings saved.",
        ["Status.ReloadingLanguage"] = "Reloading planner language...",
        ["Status.CouldNotReloadLanguage"] = "Could not reload language: {0}",
        ["Status.NotSavedYet"] = "Not saved yet",
        ["Status.LastSaved"] = "Last saved: {0}, {1}",
        ["Status.Today"] = "Today",
        ["Status.Yesterday"] = "Yesterday",
        ["Status.SourceSchemeUnavailable"] = "Source scheme is no longer available.",
        ["Status.Deleted"] = "Deleted {0}.",
        ["Status.CouldNotDeleteScheme"] = "Could not delete scheme: {0}",
        ["Status.RemovedBlueprintReferences"] = "Removed {0} blueprint references to {1}.",
        ["Status.SchemeHasNoMarkedOutputs"] = "Scheme \"{0}\" has no marked outputs.",
        ["Status.SchemeOutputsUnavailable"] = "Scheme \"{0}\" outputs are not available in the current catalog.",
        ["Status.AddedBlueprintSource"] = "Added blueprint source from {0} with {1} outputs.",
        ["Status.AddedScheme"] = "Added scheme {0}.",
        ["Status.CouldNotAddScheme"] = "Could not add scheme: {0}",
        ["Status.SchemeFolderChanged"] = "Scheme folder changed.",
        ["Status.ResourceNotAvailableForConnection"] = "This resource {0}",
        ["Status.PortsNotCompatible"] = "Ports are not compatible.",
        ["Status.ConnectionAlreadyExists"] = "Connection already exists.",
        ["Status.ConnectedMachines"] = "Connected machines.",
        ["Status.NoCompatibleMachines"] = "No compatible machines found.",
        ["Status.FoundCompatibleMachines"] = "Found {0} compatible machines.",
        ["Status.CouldNotLoadSuggestions"] = "Could not load suggestions: {0}",
        ["Status.NodeMarkedOutputOnly"] = "Node marked as output-only source.",
        ["Status.NodeInputsRestored"] = "Node input requirements restored.",
        ["Status.NodeMarkedSchemeOutput"] = "Node marked as scheme output.",
        ["Status.NodeRemovedSchemeOutputs"] = "Node removed from scheme outputs.",
        ["Status.CorporationLevelsUpdated"] = "Corporation levels updated.",
    };

    public static string T(string key)
    {
        var resourceKey = "Ui." + key;
        if (Application.Current?.TryFindResource(resourceKey) is string value && !string.IsNullOrWhiteSpace(value))
        {
            return value;
        }

        return Fallback.TryGetValue(key, out var fallback) ? fallback : key;
    }

    public static string Format(string key, params object[] args)
    {
        return string.Format(CultureInfo.CurrentCulture, T(key), args);
    }
}
